version: "2"
run:
  timeout: 5m
linters:
  default: none
  enable:
    - errcheck
    - govet
    - importas
    - ineffassign
    - modernize
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    importas:
      no-unaliased: true
      alias:
        - pkg: sigs.k8s.io/controller-runtime/pkg/client
          alias: kclient
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
