version: 2

project_name: "obot"

builds:
  - id: build-darwin
    main: .
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    tags:
      - kustomize_disable_go_plugin_support
    ldflags:
      - -s -w
      - -X "github.com/obot-platform/obot/pkg/version.Tag=v{{ .Version }}"
    hooks:
      post:
        - cmd: quill sign-and-notarize "{{ .Path }}" --dry-run={{ .IsSnapshot }} --ad-hoc={{ .IsSnapshot }} -vv
          env:
            - QUILL_LOG_FILE=/tmp/quill-{{ .Target }}.log

  - id: build-other
    main: .
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    tags:
      - kustomize_disable_go_plugin_support
    ldflags:
      - -s -w
      - -X "github.com/obot-platform/obot/pkg/version.Tag=v{{ .Version }}"

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

release:
  github:
    owner: "obot-platform"
    name: "obot"
  make_latest: false
  prerelease: auto

brews:
  - name: obot
    description: "Obot CLI"
    install: |
      bin.install "obot"
    homepage: "https://github.com/obot-platform/obot"
    skip_upload: auto
    directory: "Formula"
    repository:
      owner: obot-platform
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
