{{- if not .Values.secret.existingSecret -}}
{{- if not (eq (empty .Values.config.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_EMAIL) (empty .Values.secret.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_SETUP_TOKEN)) -}}
{{- fail "config.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_EMAIL and secret.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_SETUP_TOKEN must be set together" -}}
{{- end -}}
{{- if and .Values.secret.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_SETUP_TOKEN (lt (len .Values.secret.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_SETUP_TOKEN) 32) -}}
{{- fail "secret.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_SETUP_TOKEN must be at least 32 characters" -}}
{{- end -}}
{{- if not .Values.dev.useEmbeddedDb }}
{{- $_ := required "For production use, you must provide a value for `secret.OBOT_SERVER_DSN`. For testing or development purposes, you can set `dev.useEmbeddedDb` to true." .Values.secret.OBOT_SERVER_DSN -}}
{{- end }}
{{- $secretName := ( include "obot.secret.secretName" . ) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "obot.labels" . | nindent 4 }}
  name: {{ include "obot.secret.secretName" . }}
data:
  {{- $cfg := .Values.secret -}}
  {{- range $key := keys $cfg | sortAlpha }}
  {{- $value := index $cfg $key }}
  {{- if and (toString $value) (ne $key "existingSecret") }}
  {{ $key }}: {{ toString $value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if gt (len .Values.mcpImagePullSecrets) 0 }}
  OBOT_SERVER_MCPIMAGE_PULL_SECRETS: {{ include "obot.config.mcpImagePullSecrets" . | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.secret.OBOT_BOOTSTRAP_TOKEN "") (eq .Values.secret.OBOT_SERVER_LOCAL_AUTH_INITIAL_OWNER_SETUP_TOKEN "") }}
    {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
    {{- if $existing }}
      {{- $val := index $existing.data "OBOT_BOOTSTRAP_TOKEN" }}
  OBOT_BOOTSTRAP_TOKEN: {{ $val | quote }}
    {{- else }}
      {{- $random := randAlphaNum 32 }}
  OBOT_BOOTSTRAP_TOKEN: {{ $random | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end -}}
