{{- if or .Values.serviceAccount.create (include "obot.mcpOnKubernetes" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obot.serviceAccountName" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "obot.labels" . | nindent 4 }}
{{- end }}
