//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AccessControlRule) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AccessControlRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AccessControlRuleList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AccessControlRuleList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AccessControlRuleSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AccessControlRuleSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AgentCatalog) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AgentCatalog"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AgentCatalogList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AgentCatalogList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AgentCatalogSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AgentCatalogSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AgentCatalogStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AgentCatalogStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Alias) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Alias"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AliasList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AliasList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AliasSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AliasSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppNotification) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppNotification"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppNotificationList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppNotificationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppNotificationSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppNotificationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppNotificationStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppNotificationStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppPreferences) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppPreferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppPreferencesList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppPreferencesList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppPreferencesSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppPreferencesSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AppPreferencesStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AppPreferencesStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditLogExport) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuditLogExport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditLogExportList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuditLogExportList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditLogExportSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuditLogExportSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuditLogExportStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuditLogExportStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthProvider) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuthProvider"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthProviderList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuthProviderList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthProviderSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuthProviderSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in AuthProviderStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.AuthProviderStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DefaultModelAlias) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.DefaultModelAlias"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DefaultModelAliasList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.DefaultModelAliasList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DefaultModelAliasSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.DefaultModelAliasSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DefaultModelAliasStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.DefaultModelAliasStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DeploymentCondition) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.DeploymentCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EmptyStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.EmptyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitCredential) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GitCredential"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitCredentialList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GitCredentialList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitCredentialReference) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GitCredentialReference"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitCredentialReferences) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GitCredentialReferences"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitCredentialSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GitCredentialSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GitCredentialStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GitCredentialStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupRoleChange) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GroupRoleChange"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupRoleChangeList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GroupRoleChangeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in GroupRoleChangeSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.GroupRoleChangeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Harness) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Harness"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarnessList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HarnessList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarnessSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HarnessSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HarnessStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HarnessStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgent) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgent"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentAccessRule) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentAccessRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentAccessRuleList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentAccessRuleList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentAccessRuleSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentAccessRuleSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentInstance) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentInstance"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentInstanceList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentInstanceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentInstanceSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentInstanceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentInstanceStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentInstanceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPool) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolAssignment) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolAssignment"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolAssignmentList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolAssignmentList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolAssignmentSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolAssignmentSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolDefaults) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolDefaults"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolDefaultsList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolDefaultsList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolDefaultsSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolDefaultsSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentPoolStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentPoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in HostedAgentStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.HostedAgentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImagePullSecret) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ImagePullSecret"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImagePullSecretList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ImagePullSecretList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImagePullSecretSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ImagePullSecretSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImagePullSecretStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ImagePullSecretStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in K8sSettings) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.K8sSettings"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in K8sSettingsList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.K8sSettingsList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in K8sSettingsSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.K8sSettingsSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in K8sSettingsStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.K8sSettingsStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPCatalog) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPCatalog"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPCatalogList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPCatalogList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPCatalogSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPCatalogSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPCatalogStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPCatalogStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPNetworkPolicy) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPNetworkPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPNetworkPolicyList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPNetworkPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPNetworkPolicySpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPNetworkPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPNetworkPolicyStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPNetworkPolicyStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServer) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerCatalogEntry) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerCatalogEntry"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerCatalogEntryList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerCatalogEntryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerCatalogEntrySpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerCatalogEntrySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerCatalogEntryStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerCatalogEntryStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerInstance) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerInstance"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerInstanceList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerInstanceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerInstanceSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerInstanceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPServerStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPServerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPTunnel) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPTunnel"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPTunnelList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPTunnelList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPTunnelSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPTunnelSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPWebhookValidation) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPWebhookValidation"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPWebhookValidationList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPWebhookValidationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPWebhookValidationSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPWebhookValidationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MCPWebhookValidationStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MCPWebhookValidationStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAsset) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAsset"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAssetList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAssetList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAssetSource) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAssetSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAssetSourceList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAssetSourceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAssetSourceSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAssetSourceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAssetSourceStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAssetSourceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MDMAssetSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MDMAssetSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MessagePolicy) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MessagePolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MessagePolicyList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MessagePolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MessagePolicySpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.MessagePolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Model) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Model"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelAccessPolicy) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelAccessPolicy"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelAccessPolicyList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelAccessPolicyList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelAccessPolicySpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelAccessPolicySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfo) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfo"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfoList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfoList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfoSource) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfoSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfoSourceList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfoSourceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfoSourceSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfoSourceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfoSourceStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfoSourceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelInfoSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelInfoSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelProvider) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelProvider"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelProviderList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelProviderList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelProviderSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelProviderSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelProviderStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelProviderStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ModelStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ModelStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NanobotAgent) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.NanobotAgent"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NanobotAgentList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.NanobotAgentList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NanobotAgentSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.NanobotAgentSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NanobotAgentStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.NanobotAgentStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthAuthRequest) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthAuthRequest"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthAuthRequestList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthAuthRequestList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthAuthRequestSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthAuthRequestSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthAuthRequestStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthAuthRequestStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthClient) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthClient"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthClientList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthClientList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthClientSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthClientSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthClientStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthClientStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthMetadata) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthMetadata"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthToken) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthToken"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthTokenList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthTokenList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthTokenSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthTokenSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OAuthTokenStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OAuthTokenStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OktaGroupMigration) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OktaGroupMigration"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OktaGroupMigrationList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OktaGroupMigrationList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in OktaGroupMigrationSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.OktaGroupMigrationSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PodSecurityAdmissionSettings) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PodSecurityAdmissionSettings"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PowerUserWorkspace) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PowerUserWorkspace"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PowerUserWorkspaceList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PowerUserWorkspaceList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PowerUserWorkspaceSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PowerUserWorkspaceSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PowerUserWorkspaceStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PowerUserWorkspaceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Project) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Project"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProjectList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ProjectList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProjectSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ProjectSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProjectStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ProjectStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProjectV2) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ProjectV2"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ProjectV2List) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ProjectV2List"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PublishedArtifact) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PublishedArtifact"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PublishedArtifactList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PublishedArtifactList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PublishedArtifactSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PublishedArtifactSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in PublishedArtifactStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.PublishedArtifactStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Ref) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Ref"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Schedule) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Schedule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ScheduledAuditLogExport) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ScheduledAuditLogExport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ScheduledAuditLogExportList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ScheduledAuditLogExportList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ScheduledAuditLogExportSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ScheduledAuditLogExportSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ScheduledAuditLogExportStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.ScheduledAuditLogExportStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Skill) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.Skill"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillAccessRule) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillAccessRule"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillAccessRuleList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillAccessRuleList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillAccessRuleSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillAccessRuleSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillRepository) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillRepository"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillRepositoryList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillRepositoryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillRepositorySpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillRepositorySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillRepositoryStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillRepositoryStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SkillStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SkillStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPCatalog) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPCatalog"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPCatalogList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPCatalogList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPCatalogSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPCatalogSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPCatalogStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPCatalogStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServer) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerCatalogEntry) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerCatalogEntry"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerCatalogEntryList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerCatalogEntryList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerCatalogEntrySpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerCatalogEntrySpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerCatalogEntryStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerCatalogEntryStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SystemMCPServerStatus) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.SystemMCPServerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefaultRoleSetting) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserDefaultRoleSetting"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefaultRoleSettingList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserDefaultRoleSettingList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDefaultRoleSettingSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserDefaultRoleSettingSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDelete) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserDelete"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDeleteList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserDeleteList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserDeleteSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserDeleteSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserGroupChange) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserGroupChange"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserGroupChangeList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserGroupChangeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserGroupChangeSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserGroupChangeSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserRoleChange) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserRoleChange"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserRoleChangeList) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserRoleChangeList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in UserRoleChangeSpec) OpenAPIModelName() string {
	return "com.github.obot-platform.obot.pkg.storage.apis.obot.obot.ai.v1.UserRoleChangeSpec"
}
