package compositemigration

import (
	"context"
	"crypto/sha1"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"maps"
	"slices"
	"uuid"

	"github.com/obot-platform/nah/pkg/name"
	"github.com/obot-platform/nah/pkg/router"
	"github.com/obot-platform/obot/apiclient/types"
	gateway "github.com/obot-platform/obot/pkg/gateway/client"
	gatewaytypes "github.com/obot-platform/obot/pkg/gateway/types"
	v1 "github.com/obot-platform/obot/pkg/storage/apis/obot.obot.ai/v1"
	"github.com/obot-platform/obot/pkg/system"
	"github.com/obot-platform/obot/pkg/utils"
	"github.com/obot-platform/obot/pkg/vmcp"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/fields"
	kclient "sigs.k8s.io/controller-runtime/pkg/client"
)

type Handler struct {
	reveal    func(context.Context, []string, string) (gatewaytypes.Credential, error)
	upsert    func(context.Context, gatewaytypes.Credential) error
	copyOAuth func(context.Context, string, string, string) error
}

// The removed schema is decoded only at this storage migration boundary.
type legacyManifest struct {
	types.MCPServerCatalogEntryManifest
	Env          []types.MCPEnv `json:"env"`
	RemoteConfig *struct {
		types.RemoteCatalogConfig
		Headers []types.MCPHeader `json:"headers"`
	} `json:"remoteConfig"`
	CompositeConfig *struct {
		ComponentServers []legacyComponent `json:"componentServers"`
	} `json:"compositeConfig"`
}

type legacyComponent struct {
	CatalogEntryID string               `json:"catalogEntryID"`
	MCPServerID    string               `json:"mcpServerID"`
	Manifest       legacyManifest       `json:"manifest"`
	ToolOverrides  []types.ToolOverride `json:"toolOverrides"`
	ToolPrefix     string               `json:"toolPrefix"`
}

func New(client *gateway.Client) *Handler {
	return &Handler{reveal: client.RevealCredential, upsert: client.UpsertCredential, copyOAuth: client.CopyMCPOAuthTokens}
}

// MigrateAll runs before controllers and API traffic start. Deleting sources may
// still have finalizers; their cleanup must be left to the controllers.
func (h *Handler) MigrateAll(ctx context.Context, client kclient.WithWatch) error {
	var entries v1.MCPServerCatalogEntryList
	if err := client.List(ctx, &entries); err != nil {
		return err
	}
	for i := range entries.Items {
		entry := &entries.Items[i]
		if err := h.Migrate(router.Request{Ctx: ctx, Client: client, Object: entry}, nil); err != nil {
			return fmt.Errorf("migrate composite catalog entry %s/%s: %w", entry.Namespace, entry.Name, err)
		}
	}

	// A composite without a recoverable source must not silently survive startup.
	var servers v1.MCPServerList
	if err := client.List(ctx, &servers); err != nil {
		return err
	}
	for _, server := range servers.Items {
		if server.Spec.Manifest.Runtime == types.RuntimeComposite && server.DeletionTimestamp.IsZero() {
			return fmt.Errorf("composite MCP server %s/%s was not migrated; restore its source catalog entry before restarting", server.Namespace, server.Name)
		}
	}
	return nil
}

func (m legacyManifest) flattened() types.MCPServerCatalogEntryManifest {
	result := m.MCPServerCatalogEntryManifest
	for _, item := range m.Env {
		result.Config = append(result.Config, types.ConfigFromEnv(item))
	}
	if m.RemoteConfig != nil {
		result.RemoteConfig = &m.RemoteConfig.RemoteCatalogConfig
		for _, item := range m.RemoteConfig.Headers {
			result.Config = append(result.Config, types.ConfigFromHeader(item))
		}
	}
	return result
}

func migrationName(prefix, namespace, name string) string {
	// Stable across retries even when a process stops between credential and object writes.
	// Preserve the UUIDv5 OID names generated by the original migration.
	oid := uuid.MustParse("6ba7b812-9dad-11d1-80b4-00c04fd430c8")
	hash := sha1.Sum(append(oid[:], []byte(namespace+"/"+name)...))
	id := uuid.UUID(hash[:16])
	id[6] = (id[6] & 0x0f) | 0x50
	id[8] = (id[8] & 0x3f) | 0x80
	return prefix + id.String()
}

func (h *Handler) Migrate(req router.Request, _ router.Response) error {
	entry := req.Object.(*v1.MCPServerCatalogEntry)
	if entry.Spec.Manifest.Runtime != types.RuntimeComposite {
		return nil
	}
	var legacy legacyManifest
	if err := json.Unmarshal(entry.Spec.LegacyCompositeManifest, &legacy); err != nil { //nolint:staticcheck // This migration is the consumer of the deprecated snapshot.
		return fmt.Errorf("decode legacy composite %q: %w", entry.Name, err)
	}
	if legacy.CompositeConfig == nil || len(legacy.CompositeConfig.ComponentServers) == 0 {
		return fmt.Errorf("composite %q has no recoverable component snapshots; retaining source", entry.Name)
	}
	var parents v1.MCPServerList
	if err := req.List(&parents, &kclient.ListOptions{Namespace: entry.Namespace, FieldSelector: fields.OneTermEqualSelector("spec.mcpServerCatalogEntryName", entry.Name)}); err != nil {
		return err
	}
	target, static, err := h.buildVMCP(req, entry, legacy)
	if err != nil {
		return err
	}
	var existing v1.VMCP
	if err := req.Get(&existing, target.Namespace, target.Name); err == nil {
		if existing.Spec.LegacySlug != entry.Name {
			return fmt.Errorf("migration target %q has different ownership", target.Name)
		}
		target = existing
	} else if !apierrors.IsNotFound(err) {
		return err
	} else {
		if err := h.save(req.Ctx, vmcp.StaticConfigurationCredentialContext(target.Name), static); err != nil {
			return err
		}
		if err := req.Client.Create(req.Ctx, &target); err != nil {
			return err
		}
	}
	for i := range parents.Items {
		parent := &parents.Items[i]
		if !parent.DeletionTimestamp.IsZero() {
			continue
		}
		if parent.Spec.Manifest.Runtime != types.RuntimeComposite || parent.Spec.CompositeName != "" {
			return fmt.Errorf("unexpected dependent server %q; retaining composite source", parent.Name)
		}
		if err := h.migrateInstance(req, target, parent); err != nil {
			return fmt.Errorf("migrate composite connection %q: %w", parent.Name, err)
		}
	}
	return kclient.IgnoreNotFound(req.Client.Delete(req.Ctx, entry))
}

func (h *Handler) buildVMCP(req router.Request, entry *v1.MCPServerCatalogEntry, legacy legacyManifest) (v1.VMCP, map[string]string, error) {
	target := v1.VMCP{
		Name: migrationName(system.VMCPPrefix, entry.Namespace, entry.Name), Namespace: entry.Namespace,
		Finalizers: []string{v1.VMCPFinalizer},
		Spec: v1.VMCPSpec{
			LegacySlug: entry.Name,
			Manifest: types.VMCPManifest{
				DisplayName: entry.Spec.Manifest.Name,
				Description: entry.Spec.Manifest.Description,
				Icon:        entry.Spec.Manifest.Icon,
				// Legacy connections have independent configuration and may share an owner.
				ForceSingleUser: true,
				Profiles:        []types.VMCPProfile{},
			},
		},
	}
	if target.Spec.Manifest.DisplayName == "" {
		target.Spec.Manifest.DisplayName = entry.Name
	}
	var rules v1.AccessControlRuleList
	if err := req.List(&rules, &kclient.ListOptions{Namespace: entry.Namespace}); err != nil {
		return target, nil, err
	}
	for _, rule := range rules.Items {
		if rule.Spec.MCPCatalogID != entry.Spec.MCPCatalogName || rule.Spec.PowerUserWorkspaceID != entry.Spec.PowerUserWorkspaceID {
			continue
		}
		for _, resource := range rule.Spec.Manifest.Resources {
			if (resource.Type == types.ResourceTypeSelector && resource.ID == "*") || (resource.Type == types.ResourceTypeMCPServerCatalogEntry && resource.ID == entry.Name) {
				target.Spec.Manifest.Profiles = append(target.Spec.Manifest.Profiles, types.VMCPProfile{Name: rule.Name, Subjects: rule.Spec.Manifest.Subjects, AllowAllTools: true})
				break
			}
		}
	}
	if entry.Spec.PowerUserWorkspaceID != "" {
		var workspace v1.PowerUserWorkspace
		if err := req.Get(&workspace, entry.Namespace, entry.Spec.PowerUserWorkspaceID); err != nil {
			return target, nil, err
		}
		// Preserve existing workspace sharing as explicit grants, never a wildcard.
		target.Spec.Manifest.Profiles = append(target.Spec.Manifest.Profiles, types.VMCPProfile{Name: "owner", Subjects: []types.Subject{{Type: types.SubjectTypeUser, ID: workspace.Spec.UserID}}, AllowAllTools: true})
	}
	static := map[string]string{}
	for _, old := range legacy.CompositeConfig.ComponentServers {
		manifest := old.Manifest.flattened()
		id, catalogID := old.CatalogEntryID, entry.Spec.MCPCatalogName

		// We have seen instances where this is an MCPServer ID, which is wrong. Skip such things.
		if system.IsMCPServerID(id) {
			slog.WarnContext(req.Ctx, "catalog entry ID is actually an MCP server ID, skipping component", "id", id, "entry_name", entry.Name)
			continue
		}

		values := map[string]string{}
		var shared *v1.MCPServer
		if old.MCPServerID != "" {
			shared = &v1.MCPServer{}
			if err := req.Get(shared, entry.Namespace, old.MCPServerID); err != nil {
				return target, nil, err
			}
			var err error
			manifest, err = flattenServer(shared.Spec.Manifest)
			if err != nil {
				return target, nil, err
			}
			id = old.MCPServerID
			catalogID = shared.Spec.MCPCatalogID
			values, err = h.read(req.Ctx, serverCredentialContext(*shared), shared.Name)
			if err != nil {
				return target, nil, err
			}
		}
		if id == "" || manifest.Runtime == "" || manifest.Runtime == types.RuntimeComposite {
			return target, nil, fmt.Errorf("invalid composite component %q", id)
		}
		component := types.VMCPComponent{ID: id, Name: manifest.Name, MCPCatalogID: catalogID, MCPServerCatalogEntryID: id, CatalogEntry: types.MCPServerCatalogEntrySnapshot{Manifest: manifest}, ToolOverrides: old.ToolOverrides, ToolPrefix: old.ToolPrefix}
		if shared != nil && shared.Spec.MCPServerCatalogEntryName != "" {
			component.MCPServerCatalogEntryID = shared.Spec.MCPServerCatalogEntryName
			component.CatalogEntry.UnsupportedTools = slices.Clone(shared.Spec.UnsupportedTools)
		}
		if component.Name == "" {
			component.Name = id
		}
		for i := range component.CatalogEntry.Manifest.Config {
			item := &component.CatalogEntry.Manifest.Config[i]
			policy := types.VMCPConfigurationPolicyUserAllowed
			value := item.Value
			if v, ok := values[item.Key]; ok {
				value = v
			}
			if value != "" || shared != nil {
				policy = types.VMCPConfigurationPolicyFixed
			}
			if shared != nil {
				for _, header := range shared.Spec.Manifest.UserConfig() {
					if header.Key == item.Key {
						policy = types.VMCPConfigurationPolicyUserAllowed
					}
				}
			}
			if policy == types.VMCPConfigurationPolicyFixed {
				static[vmcp.ConfigurationKey(id, item.Key)] = value
			}
			item.Value = ""
			component.Configuration = append(component.Configuration, types.VMCPConfigurationPolicy{Key: item.Key, Policy: policy})
		}
		component.OAuthCredentialID = vmcp.StaticOAuthCredentialReference(manifest, id)
		if shared != nil {
			component.OAuthCredentialID = vmcp.StaticOAuthCredentialReference(manifest, shared.Spec.MCPServerCatalogEntryName)
		}
		component.SourceDigest = utils.Digest(component.CatalogEntry)
		target.Spec.Manifest.Components = append(target.Spec.Manifest.Components, component)
	}
	vmcp.SetStaticConfigurationHashes(&target, static)
	return target, static, target.Spec.Manifest.Validate()
}

func flattenServer(server types.MCPServerManifest) (types.MCPServerCatalogEntryManifest, error) {
	// Startup has already flattened stored server manifests.
	return server.ConvertToCatalogEntry(), nil
}

func serverCredentialContext(server v1.MCPServer) string {
	owner := server.Spec.UserID
	if server.Spec.MCPCatalogID != "" {
		owner = server.Spec.MCPCatalogID
	} else if server.Spec.PowerUserWorkspaceID != "" {
		owner = server.Spec.PowerUserWorkspaceID
	}
	return owner + "-" + server.Name
}

func (h *Handler) read(ctx context.Context, scope, name string) (map[string]string, error) {
	credential, err := h.reveal(ctx, []string{scope}, name)
	if errors.As(err, &gateway.CredentialNotFoundError{}) {
		return map[string]string{}, nil
	}
	return credential.Secrets, err
}

func (h *Handler) save(ctx context.Context, scope string, values map[string]string) error {
	return h.upsert(ctx, gatewaytypes.Credential{Context: scope, Name: vmcp.ConfigurationCredentialName(), Secrets: values})
}

func (h *Handler) migrateInstance(req router.Request, target v1.VMCP, parent *v1.MCPServer) error {
	instance := v1.VMCPInstance{
		Name:       migrationName(system.VMCPInstancePrefix, parent.Namespace, parent.Name),
		Namespace:  parent.Namespace,
		Finalizers: []string{v1.VMCPInstanceFinalizer},
	}
	if err := req.Get(&instance, instance.Namespace, instance.Name); err == nil {
		if instance.Spec.LegacySlug != parent.Name || instance.Spec.UserID != parent.Spec.UserID || instance.Spec.Manifest.VMCPID != target.Name {
			return fmt.Errorf("migration instance has different ownership")
		}
		return kclient.IgnoreNotFound(req.Client.Delete(req.Ctx, parent))
	} else if !apierrors.IsNotFound(err) {
		return err
	}
	if parent.Spec.Manifest.CompositeConfig == nil {
		return fmt.Errorf("missing component snapshots")
	}
	instance.Spec.LegacySlug = parent.Name
	instance.Spec.LegacyCreatedAt = parent.CreationTimestamp.DeepCopy()
	instance.Spec.UserID = parent.Spec.UserID
	instance.Spec.Manifest.VMCPID = target.Name
	var children v1.MCPServerList
	if err := req.List(&children, &kclient.ListOptions{Namespace: parent.Namespace, FieldSelector: fields.OneTermEqualSelector("spec.compositeName", parent.Name)}); err != nil {
		return err
	}
	var connections v1.MCPServerInstanceList
	if err := req.List(&connections, &kclient.ListOptions{Namespace: parent.Namespace, FieldSelector: fields.OneTermEqualSelector("spec.compositeName", parent.Name)}); err != nil {
		return err
	}
	configuration := map[string]string{}
	for _, old := range parent.Spec.Manifest.CompositeConfig.ComponentServers {
		id := old.CatalogEntryID
		if system.IsMCPServerID(id) {
			slog.WarnContext(req.Ctx, "invalid catalog entry ID", "id", id, "parent", parent.Name)
			continue
		}

		if old.MCPServerID != "" {
			id = old.MCPServerID
		}
		index := slices.IndexFunc(target.Spec.Manifest.Components, func(c types.VMCPComponent) bool { return c.ID == id })
		if index < 0 {
			return fmt.Errorf("component %q no longer exists in migrated vMCP", id)
		}
		component := target.DeepCopy().Spec.Manifest.Components[index]
		component.SourceDigest = utils.Digest([]any{component, target.Spec.ComponentStaticConfigurationHashes[component.ID]})
		component.ToolOverrides, component.ToolPrefix = old.ToolOverrides, old.ToolPrefix
		values := map[string]string{}
		if old.CatalogEntryID != "" {
			manifest, err := flattenServer(old.Manifest)
			if err != nil {
				return err
			}
			for _, item := range manifest.Config {
				if item.Value != "" {
					values[item.Key] = item.Value
				}
			}
			for i := range manifest.Config {
				manifest.Config[i].Value = ""
			}
			component.CatalogEntry.Manifest = manifest
			if manifest.Name != "" {
				component.Name = manifest.Name
			}
		}
		for _, child := range children.Items {
			if child.Spec.MCPServerCatalogEntryName != id {
				continue
			}
			secret, err := h.read(req.Ctx, serverCredentialContext(child), child.Name)
			if err != nil {
				return err
			}
			maps.Copy(values, secret)
			if h.copyOAuth != nil {
				if err := h.copyOAuth(req.Ctx, parent.Spec.UserID, child.Name, name.SafeConcatName(system.MCPServerPrefix+instance.Name, id)); err != nil {
					return err
				}
			}
		}
		if old.MCPServerID != "" && h.copyOAuth != nil {
			if err := h.copyOAuth(req.Ctx, parent.Spec.UserID, old.MCPServerID, name.SafeConcatName(system.MCPServerPrefix+instance.Name, id)); err != nil {
				return err
			}
		}
		for _, connection := range connections.Items {
			if connection.Spec.MCPServerName != id {
				continue
			}
			secret, err := h.read(req.Ctx, connection.Spec.UserID+"-"+connection.Name, connection.Name)
			if err != nil {
				return err
			}
			maps.Copy(values, secret)
		}
		for key, value := range values {
			configuration[vmcp.ConfigurationKey(id, key)] = value
			index := slices.IndexFunc(component.Configuration, func(p types.VMCPConfigurationPolicy) bool { return p.Key == key })
			if index < 0 {
				component.Configuration = append(component.Configuration, types.VMCPConfigurationPolicy{Key: key, Policy: types.VMCPConfigurationPolicyUserAllowed})
			} else {
				component.Configuration[index].Policy = types.VMCPConfigurationPolicyUserAllowed
			}
		}
		if old.Disabled {
			instance.Spec.LegacyDisabledComponents = append(instance.Spec.LegacyDisabledComponents, id)
		}
		instance.Spec.LegacyComponents = append(instance.Spec.LegacyComponents, component)
	}
	// Components added since this connection's snapshot were not enabled by its owner.
	for _, component := range target.Spec.Manifest.Components {
		if !slices.ContainsFunc(instance.Spec.LegacyComponents, func(c types.VMCPComponent) bool { return c.ID == component.ID }) {
			instance.Spec.LegacyDisabledComponents = append(instance.Spec.LegacyDisabledComponents, component.ID)
		}
	}
	if err := h.save(req.Ctx, vmcp.InstanceConfigurationCredentialContext(instance.Name), configuration); err != nil {
		return err
	}
	instance.Status.UserConfigurationHash = utils.Digest(configuration)
	if err := req.Client.Create(req.Ctx, &instance); err != nil {
		return err
	}
	return kclient.IgnoreNotFound(req.Client.Delete(req.Ctx, parent))
}
