name: go

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - 'feat/*'
    paths-ignore:
      - chart/**
      - ui/user/**

jobs:
  lint:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: make build

      - name: Validate Go Code
        run: make validate-go-code
