name: Helm Chart

permissions:
  contents: read
  packages: read

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helm.yml
      - chart/**
  pull_request:
    branches:
      - main
      - 'feat/*'
    paths:
      - .github/workflows/helm.yml
      - chart/**

jobs:
  lint:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint chart --set dev.useEmbeddedDb=true

      - name: Render Helm chart
        run: helm template obot chart --namespace obot --set dev.useEmbeddedDb=true

  build:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Render chart
        run: |
          helm template test-release ./chart --set dev.useEmbeddedDb=true > rendered.yaml

      - name: Log in to GitHub Packages
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: docker://ghcr.io/yannh/kubeconform:v0.8.0
        with:
          entrypoint: "/kubeconform"
          args: "-summary -output json rendered.yaml"

      - name: Build Helm chart package
        run: |
          mkdir -p packaged
          helm package chart --destination packaged

      - name: Verify Helm chart package
        run: test -f packaged/*.tgz
